# Generated by Django 2.1.7 on 2019-03-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageboard', '0002_auto_20190312_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='description',
            field=models.CharField(default='This board talks about stuff', max_length=280),
            preserve_default=False,
        ),
    ]
