# Generated by Django 2.1.7 on 2019-03-28 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messageboard', '0005_auto_20190328_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'permissions': (('delete_this_board', 'Delete this board'),)},
        ),
    ]
